name: comanda
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  equatable: ^2.0.3
  http: ^0.13.4
  get_it: ^7.1.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  provider: ^6.0.3


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

 